export const HYDRATE_VIBES = 'HYDRATE_VIBES';
export const UPDATE_CURRENT_VIBE = 'UPDATE_CURRENT_VIBE';
export const UPDATE_CREATORS = 'UPDATE_CREATORS';
// export const UPDATE_SONGS = 'UPDATE_SONGS';
